# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='cuerpoComentario',
            new_name='Comentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='idEntrada',
            new_name='id_message',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechaComentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
