# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20170127_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Comentario',
            new_name='Texto_Comentario',
        ),
    ]
